POST http://localhost:8001/login
Content-Type: application/json

{
    "username": "mario",
    "password": "securePassword"
}

###

POST http://localhost:8001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlvIiwiaWF0IjoxNjUyMjIyNzk4fQ.ZM-7WhYc6F66VDJvDX_UEQvIUr_A4xe0QfkVpowC_q0"
}

###

DELETE http://localhost:8001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlvIiwiaWF0IjoxNjUyMjIyNzk4fQ.ZM-7WhYc6F66VDJvDX_UEQvIUr_A4xe0QfkVpowC_q0"
}

###

GET http://localhost:8000/v1.1/misurazioni?$lookup=1&tipoInquinante=pm10&$where={ "stazione.comune": "Verona" }
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlvIiwiaWF0IjoxNjUyMjI4MTAxLCJleHAiOjE2NTIyMjk5MDF9.0YCi1XqM9d7PpdQEmn1yBcZnI8M3S7zHHX8FS5-XSaA

###

GET http://localhost:8000/v1.1/misurazioni
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlvIiwiaWF0IjoxNjUyMjI4MTAxLCJleHAiOjE2NTIyMjk5MDF9.0YCi1XqM9d7PpdQEmn1yBcZnI8M3S7zHHX8FS5-XSaA

###

GET http://localhost:8000/v1.1/stats?$group={"_id":{"month":{"$month":"$data"},"tipoInquinante":"$tipoInquinante","provincia":"$stazione"},"mis media":{"$avg":"$mis"},"tot mis":{"$sum":"$mis"},"max mis":{"$max":"$mis"},"misurazioni":{"$sum":1}}